[2024-01-31T00:06:26.318+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: meteo_dag.print_meteo scheduled__2024-01-21T00:00:00+00:00 [queued]>
[2024-01-31T00:06:26.328+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: meteo_dag.print_meteo scheduled__2024-01-21T00:00:00+00:00 [queued]>
[2024-01-31T00:06:26.328+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-31T00:06:26.357+0100] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): print_meteo> on 2024-01-21 00:00:00+00:00
[2024-01-31T00:06:26.364+0100] {standard_task_runner.py:60} INFO - Started process 19996 to run task
[2024-01-31T00:06:26.372+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'meteo_dag', 'print_meteo', 'scheduled__2024-01-21T00:00:00+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/meteoDag.py', '--cfg-path', '/tmp/tmpbjpnsx5i']
[2024-01-31T00:06:26.376+0100] {standard_task_runner.py:88} INFO - Job 63: Subtask print_meteo
[2024-01-31T00:06:26.432+0100] {task_command.py:423} INFO - Running <TaskInstance: meteo_dag.print_meteo scheduled__2024-01-21T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-31T00:06:26.528+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='meteo_dag' AIRFLOW_CTX_TASK_ID='print_meteo' AIRFLOW_CTX_EXECUTION_DATE='2024-01-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-21T00:00:00+00:00'
[2024-01-31T00:06:26.825+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-01-31T00:06:26.826+0100] {client.py:496} INFO - Writing to '/user/datalake/meteobrut/Datajours4/2024-01-31.json'.
[2024-01-31T00:06:27.382+0100] {logging_mixin.py:188} INFO - Forecast data has been saved to /user/datalake/meteobrut/Datajours4/2024-01-31.json on HDFS
[2024-01-31T00:06:27.588+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-01-31T00:06:27.589+0100] {client.py:496} INFO - Writing to '/user/datalake/meteobrut/DataCurrent/2024-01-31/00_06_24.json'.
[2024-01-31T00:06:28.080+0100] {logging_mixin.py:188} INFO - Current weather data has been saved to /user/datalake/meteobrut/DataCurrent/2024-01-31/00_06_24.json on HDFS
[2024-01-31T00:06:28.083+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-01-31T00:06:28.093+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=meteo_dag, task_id=print_meteo, execution_date=20240121T000000, start_date=20240130T230626, end_date=20240130T230628
[2024-01-31T00:06:28.148+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-31T00:06:28.163+0100] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
