[2024-01-31T01:00:11.430+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: meteo_dag.print_meteo scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-01-31T01:00:11.452+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: meteo_dag.print_meteo scheduled__2024-01-30T00:00:00+00:00 [queued]>
[2024-01-31T01:00:11.453+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-01-31T01:00:11.517+0100] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): print_meteo> on 2024-01-30 00:00:00+00:00
[2024-01-31T01:00:11.586+0100] {standard_task_runner.py:60} INFO - Started process 26151 to run task
[2024-01-31T01:00:11.692+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'meteo_dag', 'print_meteo', 'scheduled__2024-01-30T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/meteoDag.py', '--cfg-path', '/tmp/tmpt46lcc0u']
[2024-01-31T01:00:11.760+0100] {standard_task_runner.py:88} INFO - Job 81: Subtask print_meteo
[2024-01-31T01:00:12.667+0100] {task_command.py:423} INFO - Running <TaskInstance: meteo_dag.print_meteo scheduled__2024-01-30T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-01-31T01:00:13.091+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='meteo_dag' AIRFLOW_CTX_TASK_ID='print_meteo' AIRFLOW_CTX_EXECUTION_DATE='2024-01-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-30T00:00:00+00:00'
[2024-01-31T01:00:13.629+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-01-31T01:00:13.634+0100] {client.py:496} INFO - Writing to '/user/datalake/meteobrut/Datajours4/2024-01-31.json'.
[2024-01-31T01:00:14.898+0100] {logging_mixin.py:188} INFO - Forecast data has been saved to /user/datalake/meteobrut/Datajours4/2024-01-31.json on HDFS
[2024-01-31T01:00:15.193+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-01-31T01:00:15.193+0100] {client.py:496} INFO - Writing to '/user/datalake/meteobrut/DataCurrent/2024-01-31/01_00_05.json'.
[2024-01-31T01:00:15.324+0100] {logging_mixin.py:188} INFO - Current weather data has been saved to /user/datalake/meteobrut/DataCurrent/2024-01-31/01_00_05.json on HDFS
[2024-01-31T01:00:15.330+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-01-31T01:00:15.343+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=meteo_dag, task_id=print_meteo, execution_date=20240130T000000, start_date=20240131T000011, end_date=20240131T000015
[2024-01-31T01:00:15.433+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-31T01:00:15.451+0100] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
