[2024-02-02T08:36:43.770+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: meteo_dag.print_meteo scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-02-02T08:36:43.793+0100] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: meteo_dag.print_meteo scheduled__2024-02-01T00:00:00+00:00 [queued]>
[2024-02-02T08:36:43.796+0100] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-02-02T08:36:43.875+0100] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): print_meteo> on 2024-02-01 00:00:00+00:00
[2024-02-02T08:36:43.918+0100] {standard_task_runner.py:60} INFO - Started process 23427 to run task
[2024-02-02T08:36:43.938+0100] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'meteo_dag', 'print_meteo', 'scheduled__2024-02-01T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/meteoDag.py', '--cfg-path', '/tmp/tmp4d2g7vic']
[2024-02-02T08:36:43.947+0100] {standard_task_runner.py:88} INFO - Job 89: Subtask print_meteo
[2024-02-02T08:36:44.294+0100] {task_command.py:423} INFO - Running <TaskInstance: meteo_dag.print_meteo scheduled__2024-02-01T00:00:00+00:00 [running]> on host ubuntu.ubuntu.virtualbox.org
[2024-02-02T08:36:44.719+0100] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='meteo_dag' AIRFLOW_CTX_TASK_ID='print_meteo' AIRFLOW_CTX_EXECUTION_DATE='2024-02-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-01T00:00:00+00:00'
[2024-02-02T08:36:45.528+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-02T08:36:45.534+0100] {client.py:496} INFO - Writing to '/user/datalake/meteobrut/Datajours4/2024-02-02.json'.
[2024-02-02T08:36:47.651+0100] {logging_mixin.py:188} INFO - Forecast data has been saved to /user/datalake/meteobrut/Datajours4/2024-02-02.json on HDFS
[2024-02-02T08:36:48.378+0100] {client.py:192} INFO - Instantiated <InsecureClient(url='http://localhost:9870')>.
[2024-02-02T08:36:48.379+0100] {client.py:496} INFO - Writing to '/user/datalake/meteobrut/DataCurrent/2024-02-02/08_36_38.json'.
[2024-02-02T08:36:48.618+0100] {logging_mixin.py:188} INFO - Current weather data has been saved to /user/datalake/meteobrut/DataCurrent/2024-02-02/08_36_38.json on HDFS
[2024-02-02T08:36:48.627+0100] {python.py:201} INFO - Done. Returned value was: None
[2024-02-02T08:36:48.649+0100] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=meteo_dag, task_id=print_meteo, execution_date=20240201T000000, start_date=20240202T073643, end_date=20240202T073648
[2024-02-02T08:36:48.752+0100] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-02T08:36:48.798+0100] {taskinstance.py:3281} INFO - 1 downstream tasks scheduled from follow-on schedule check
